-- Vérifier ARCHIVELOG
SELECT log_mode FROM v$database;

-- Activer ARCHIVELOG si nécessaire
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;

-- Force logging
ALTER DATABASE FORCE LOGGING;

-- Standby Redo Logs
ALTER DATABASE ADD STANDBY LOGFILE GROUP 10 SIZE 200M;
ALTER DATABASE ADD STANDBY LOGFILE GROUP 11 SIZE 200M;
ALTER DATABASE ADD STANDBY LOGFILE GROUP 12 SIZE 200M;

-- Paramètres Data Guard
ALTER SYSTEM SET LOG_ARCHIVE_CONFIG='DG_CONFIG=(ORCL_PRI,ORCL_STBY)' SCOPE=BOTH;

ALTER SYSTEM SET LOG_ARCHIVE_DEST_1=
'LOCATION=/u01/arch VALID_FOR=(ALL_LOGFILES,ALL_ROLES) DB_UNIQUE_NAME=ORCL_PRI' SCOPE=BOTH;

ALTER SYSTEM SET LOG_ARCHIVE_DEST_2=
'SERVICE=ORCL_STBY ASYNC VALID_FOR=(ONLINE_LOGFILES,PRIMARY_ROLE) DB_UNIQUE_NAME=ORCL_STBY' SCOPE=BOTH;

ALTER SYSTEM SET FAL_SERVER=ORCL_STBY;
ALTER SYSTEM SET FAL_CLIENT=ORCL_PRI;
ALTER SYSTEM SET STANDBY_FILE_MANAGEMENT=AUTO;
-- RMAN Backup
rman target /
BACKUP DATABASE PLUS ARCHIVELOG;
EXIT;


-- Password file
! orapwd file=$ORACLE_HOME/dbs/orapwORCL password=oracle force=y

-- Standby controlfile
ALTER DATABASE CREATE STANDBY CONTROLFILE AS '/tmp/standby.ctl';

-- RMAN backup
EXIT;
----------------------
-- stabdy_setup
-- initORCL.ora
DB_NAME=ORCL
DB_UNIQUE_NAME=ORCL_STBY
CONTROL_FILES=/u01/oradata/ORCL/control01.ctl
LOG_ARCHIVE_CONFIG='DG_CONFIG=(ORCL_PRI,ORCL_STBY)'
LOG_ARCHIVE_DEST_1='LOCATION=/u01/arch VALID_FOR=
(ALL_LOGFILES,ALL_ROLES) DB_UNIQUE_NAME=ORCL_STBY'
LOG_ARCHIVE_DEST_2='SERVICE=ORCL_PRI ASYNC VALID_FOR=
(ONLINE_LOGFILES,PRIMARY_ROLE) DB_UNIQUE_NAME=ORCL_PRI'
FAL_SERVER=ORCL_PRI
FAL_CLIENT=ORCL_STBY
STANDBY_FILE_MANAGEMENT=AUTO
-- Password file
orapwd file=$ORACLE_HOME/dbs/orapwORCL password=oracle force=y
-- Démarrage standby
STARTUP NOMOUNT;
ALTER DATABASE MOUNT STANDBY DATABASE;
rman target /
RESTORE DATABASE;
RECOVER DATABASE;
EXIT;
-- Data Guard Broker
ALTER SYSTEM SET DG_BROKER_START=TRUE;

dgmgrl sys/oracle

CREATE CONFIGURATION dg_config
AS PRIMARY DATABASE IS ORCL_PRI
CONNECT IDENTIFIER IS ORCL_PRI;

ADD DATABASE ORCL_STBY
AS CONNECT IDENTIFIER IS ORCL_STBY
MAINTAINED AS PHYSICAL;

ENABLE CONFIGURATION;

SHOW CONFIGURATION;
SHOW DATABASE ORCL_STBY;
